const SKILL_KEYWORDS = [
  "Effective Communication",
  "Problem Solving",
  "Time Management",
  "Digital Marketing",
  "English Proficiency (Written)",
  "Facebook Marketing",
  "Search Engine Marketing (SEM)",
  "Search Engine Optimization (SEO)",
  "Marketing",
  "Recruitment",
  "Creative Writing",
  "Email Marketing",
  "English Proficiency (Spoken)",
  "Google AdWords",
  "Google Analytics",
  "Instagram Marketing",
  "Social Media Marketing",
  "Business Analysis",
  "Market Analysis",
  "Marketing Campaigns",
  "Operations",
  "Accounting",
  "MS-Excel",
  "Tally",
  "Client Interaction",
  "Event Management",
  "Client Relationship",
  "Negotiation & Problem-solving",
  "Adobe After Effects",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
  "CorelDRAW",
  "Video Editing",
  "Adobe XD",
  "Figma",
  "UI & UX Design",
  "Wireframing",
  "Hindi Proficiency (Spoken)",
  "Final Cut Pro",
  "Sales pitch",
  "Canva",
  "LinkedIn Marketing",
  "MS-PowerPoint",
  "MS-Word",
  "CakePHP",
  "Sales",
  "Data Analytics",
  "MS-Office",
  "CSS",
  "HTML",
  "JavaScript",
  "ReactJS",
  "Fashion Styling",
  "Employment engagement",
  "Holiday Package Design",
  "Travel Itinerary Making",
  "Taxation",
  "Java",
  "React",
  "Spring MVC",
  "Financial literacy",
  "Hindi Proficiency (Written)",
  "YouTube Ads",
  "CRM",
  "Marathi Proficiency(Spoken)",
  "Manual Testing",
  "Quality Assurance/Quality Control (QA/QC)",
  "Computer Vision",
  "Google Workspace",
  "Interpersonal Skills",
  "Lead Generation",
  "Salesforce",
  "Bengali Proficiency (Spoken)",
  "Odia Proficiency(Spoken)",
  "WordPress",
  "3ds Max",
  "AutoCAD",
  "Google SketchUp",
  "Teaching",
  "Autodesk Revit",
  "Database Management System (DBMS)",
  "Adobe Indesign",
  "Blogging",
  "Content Writing",
  "Data Analysis",
  "C++ Programming",
  "C Programming",
  "iOS",
  "REST API",
  "Swift",
  "XML",
  "AJAX",
  "Bootstrap",
  "jQuery",
  "MongoDB",
  "MySQL",
  "Node.js",
  "Python",
  "Artificial Intelligence",
  "Business Research",
  "Mathematics",
  "Online Teaching",
  "Subject Matter Expert (SME)",
  "Adobe Creative Suite",
  "Adobe Photoshop Lightroom CC",
  "Amazon Web Services (AWS)",
  "PostgreSQL",
  "TypeScript",
  "Video Making",
  "SolidWorks",
  "Psychology",
  "Django",
  "Flask",
  "Machine Learning",
  "AngularJS",
  "HTML&CSS",
  "Apache",
  "Bash",
  "Nginx",
  "Animation",
  "Audio Making",
  "Project Management",
  "Content Marketing",
  "American English",
  "British English",
  "Proofreading",
  "Telugu Proficiency (Spoken)",
  "Facebook Ads",
  "CI/CD",
  "Selenium",
  "Software Testing",
  "Human Resource Information System (HRIS)",
  "Marketing Strategies",
  "Product Strategy",
  "Microsoft PowerApps",
  "Power BI",
  "Microsoft Project",
  "Kannada Proficiency (Spoken)",
  "Tamil Proficiency (Spoken)",
  "Jira",
  "Product Lifecycle Management(PLM)",
  "Product Management",
  "UX Research",
  "Research and Analytics",
  "Actuators",
  "Analog And Digital Electronics",
  "C/C++",
  "Communication Protocols",
  "Embedded Systems",
  "ROS",
  "Sensors",
  "LARAVEL",
  "PHP",
  "Financial Modeling",
  "Android",
  "Biology",
  "Chemistry",
  "Physics",
  "Market Research",
  "Design Thinking",
  "Engineering Drawing",
  "Actuation Systems",
  "Fundamentals Of Robotics",
  "Kinematics",
  "Solidworks/AutoCAD/Fusion360",
  "Data Science",
  "Payroll",
  "Gazebo",
  "PROTOTYPING",
  "SolidWorks/Fusion 360",
  "CAD",
  "Copywriting",
  "SAP",
  "Kannada Proficiency (Written)",
  "Malayalam Proficiency (Spoken)",
  "Malayalam Proficiency (Written)",
  "Telugu Proficiency (Written)",
  "FastAPI",
  "Git",
  "Gitlab",
  "Kubernetes",
  "Microsoft Azure",
  "Sketching",
  "Painting",
  "Digital Advertising",
  "Ruby on Rails",
  "Hadoop",
  "SQL",
  "C#",
  "Unity 3D",
  "Unity Engine",
  "Natural Language Processing (NLP)",
  "User Interface (UI) Development",
  "Statistics",
  "Flutter",
  "React Native",
  "Colour Theory for Designers",
  "CMS",
  "Sketch",
  "Tableau",
  "Enterprise Resource Planning(ERP)",
  "Manpower Planning",
  "Performance Management System",
  "Production Engineering",
  "3D Design",
  "C++",
  "Next.js",
  "Tailwind CSS",
  "Blockchain",
  "Mechanical & Electrical Product Design",
  "Google Suite (G Suite)",
  "Fashion Designing",
  "Amazon Web Server (AWS)",
  "Cloud Computing",
  "MS SQL Server",
  "Vue Js",
  "Digital Art",
  "Database Testing",
  ".NET",
  "Elasticsearch",
  "Blender 3D",
  "Autodesk Fusion 360",
  "Advanced Excel",
  "Malayalam",
  "Internet of Things (IoT)",
  "Control Systems",
  "Bubble.io",
  "Redux",
  "Express.js",
  "Compensation management",
  "HRIS",
  "Ethereum",
  "Solidity",
  "Truffle",
  "Angular 2.0",
  "Deep Learning",
  "HR branding",
  "Model View Controller(MVC)",
  "Sass",
  "Culinary Arts",
  "Audio Editing",
  "Kotlin",
  "Google Cloud Computing",
  "Neural Networks",
  "Computer Networking",
  "Photography",
  "Adobe Flash",
  "Autodesk Maya",
  "Marketing Programs",
  "Statutory compliances",
  "Training And Development",
  "Linux",
  "Unix",
  "Display Advertising",
  "Kashmiri Proficiency (Spoken)",
  "Clip Studio Paint",
  "Krita",
  "PCB Design",
  "Firebase",
  "Data Structures",
  "GNU Octave",
  "web3.js",
  "Objective C",
  "Xcode",
  "Robotics",
  "Magento",
  "MEAN/MERN Stack",
  "PCB Soldering",
  "Raspberry Pi",
  "DaVinci Resolve",
  "Embedded C",
  "MATLAB",
  "RTOS",
  "SYSTEM ADMINISTRATOR",
  "Cybersecurity",
  "Pattern making",
  "Report Writing",
  "Economics",
  "Angular 7.0",
  "Transcription",
  "CCNA",
  "SOC",
  "Google Ads",
  "Insta Ads",
  "Test",
  "Grammar & Vocabulary",
  "Proofreading & Editing",
  "Research & Analytics",
  "SEO (Search Engine Optimization)",
  "Storytelling",
  "Dart",
  "GitHub",
  "SQLite",
  "Autodesk 123D design",
  "Image Processing",
  "APIs",
  "Kannada",
  "LabVIEW",
  "Arduino",
  "Robotic Process Automation (RPA)",
  "Docker",
  "Jenkins",
  "Stock Trading",
  "GraphQL",
  "Sindhi Proficiency(Spoken)",
  "Sindhi Proficiency(Written)",
  "Assamese Proficiency (Spoken)",
  "Assamese Proficiency (Written)",
  "Computer Networks",
  "Odia Proficiency(Written)",
  "Investing",
  "Marathi Proficiency(Written)",
  "Anchoring",
  "Circuit Design",
  "Power Electronics",
  "Prospecting",
  "Bioinformatics",
  "Rhino",
  "HelioScope",
  "ANSYS",
  "Autodesk Inventor",
  "KeyShot",
  "Estimation (estimating)",
  "Cloud Firestore",
  "OAuth",
  "ThreeJS",
  "OpenCV",
  "Rust",
  "DevOps",
  "Translation",
  "Verilog",
  "VHDL",
  "Catia",
  "Tamil Proficiency (Written)",
  "Algorithms",
  "Postman",
  "Redis",
  "GUI Testing",
  "Prioritization",
  "Microbiological Techniques",
  "Cinema 4D",
  "HR Analytics",
  "Bengali Proficiency (Written)",
  "Gujarati Proficiency (Spoken)",
  "Gujarati Proficiency (Written)",
  "Embroidery making",
  "Acting Audition",
  "Adobe Audition",
  "Ethical Hacking",
  "JSON",
  "Unreal Engine",
  "Storyboarding",
  "STAAD.Pro",
  "CodeIgniter",
  "Punjabi Proficiency (Spoken)",
  "Hibernate (Java)",
  "Oracle",
  "Six Sigma",
  "C#.NET",
  "ARM Microcontroller",
  "Apache Kafka",
  "BIG DATA ANALYTICS",
  "Labour laws",
  "Network Security",
  "Plc Programming",
  "PLC SCADA",
  "Music",
  "Rapid Prototyping",
  "Arabic Proficiency (Written)",
  "French Proficiency (written)",
  "German Proficiency (Written)",
  "Japanese Proficiency (Written)",
  "Korean Proficiency (Written)",
  "Punjabi Proficiency (Written)",
  "Spanish Proficiency(Written)",
  "Urdu Proficiency(Written)",
  "EAGLE",
  "French Proficiency (spoken)",
  "Voiceover",
  "CLO3D",
  "Acting technique",
  "Substance Painter",
  "ZBrush",
  "R Programming",
  "Hyperledger",
  "Salary structure",
  "Microsoft Visual Studio",
  "Allegro Software",
  "UiPath",
  "Windows Mobile Application Development",
  "Certificate",
  "Letter of recommendation",
  "Informal dress code",
  "5 days a week",
  "Job offer",
  "Flexible work hours",
  "Free snacks & beverages",
  "SCSS",
  "NoSQL",
  "PTC Creo",
  "Analog And Digital Circuits",
  "ElectronJS",
  "Articulate 360",
  "Articulate Storyline",
  "Visual Basic (VB)",
  "Engineering Surveying",
  "Molecular Biology Techniques",
  "Molecular Medicine",
  "Audacity",
  "ERP Implementation and Deployment",
  "Responsive Webdesign",
  "Battery Management Systems",
  "Computational Neuroscience",
  "Perl",
  "Biostatistics",
  "Statistical Modeling",
  "German Proficiency (Spoken)",
  "Spanish Proficiency(Spoken)",
  "CNC Programming",
  "Cryptography",
  "Restful APIs",
  "Web3",
  "Pharmacovigilance",
  "Primavera",
  "Audiology",
  "GIMP",
  "Inkscape",
  "AI",
  "Chrome Extension API",
  "NLP",
  "React.Js",
  "FPGA Synthesis and Prototyping",
  "VLSI",
  "ASP.NET",
  "API Integration",
  "UI/UX Design",
  "LaTeX",
  "Webflow",
  "Framer Motion/GSAP",
  "Local Storage/ IndexedDB",
  "MemeAPIs",
  "Redux Toolkit/Context API",
  "JSP",
  "VS Code",
  "CAM",
  "AI/ML",
  "Blender",
  "Diffusion Models",
  "Three.js",
  "UI/UX",
  "Golang",
  "Flutter/Swift",
  "IOS Development Frameworks/Tools",
  "Eclipse (IDE)",
  "Dietetics/Nutrition",
  "ArcGIS",
  "Communication",
  "Engaging Content",
  "Story Telling",
  "Team Player",
  "Urdu Proficiency(Spoken)",
  "Adobe Dreamweaver",
  "INDUSTRIAL AUTOMATION",
  "Integromat",
  "Automation",
  "Matrix Integration",
  "API",
  "Odoo",
  "Quantity Survey (QS)",
  "Shell Scripting",
  "Engaging Content.",
  "Ios/Android Development",
  "Nepali Proficiency(Spoken)",
  "Nepali Proficiency(Written)",
  "Dancer MVC Web Framework",
  "Responsive Design",
  "Map Study",
  "DigitalOcean",
  "Heroku",
  "Ansible",
  "Terraform",
  "Web Application Security",
  "Ios/andoid Development",
  "J2EE",
  "SAS",
  "COMSOL",
  "Pinterest Marketing",
  "Analytical Skills",
  "Data Collection & Management",
  "Internet Surfing & Data Mining",
  "Microsoft Excel / Google Sheets",
  "Startup & SaaS Knowledge",
  "Web Research",
  "VAPT",
  "Servlets",
  "Distributed Computing",
  "No Match Found",
  "SharePoint",
  "Kashmiri Proficiency (written)"
];
module.exports = SKILL_KEYWORDS;